frontend:
	sh components/frontend.sh

mongodb:
	sh components/mongodb.sh

catalogue:
	sh components/catalogue.sh

cart:
	sh components/cart.sh

redis:
	sh components/redis.sh

user:
	sh components/user.sh

mysql:
	sh components/mysql.sh

shipping:
	sh components/shipping.sh

rabbitmq:
	sh components/rabbitmq.sh

payment:
	sh components/payment.sh